package com.reqai.backend.controller;

import com.reqai.backend.entity.Document;
import com.reqai.backend.service.DocumentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;

@RestController
@RequestMapping("/api/v1/documents")
@Tag(name = "1. Document Controller " , description = "Uploading file and AI analyzing transactions")
public class DocumentController {

    private final DocumentService documentService;

    public DocumentController(DocumentService documentService) {
        this.documentService = documentService;
    }

    @PostMapping(value = "/upload",consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(summary = "Upload a TXT file",description = "Customer upload requirement document and it starts the analyzing process on the back side")
    public ResponseEntity<Document> uploadDocument(@RequestParam("file")MultipartFile file){
        try {
            Document savedDocument = documentService.saveDocument(file);
            return ResponseEntity.ok(savedDocument); // 200
        }catch (IOException e){
            return ResponseEntity.internalServerError().build(); // 500
        }

    }

    // swagger draft mock methods
    @GetMapping
    @Operation(summary = "List all the documents", description = "Returns the uploaded and analyzed documents' list ")
    public ResponseEntity<String> getAllDocuments(){
        return ResponseEntity.ok("Document listi ");
    }
    @GetMapping("/{id}/analysis")
    @Operation(summary = "Get the document analysis details",description = "It returns business requirements,tasks,testScenarios data generated by AI")
    public ResponseEntity<String> getDocumentAnalysis(@PathVariable String id){
        return ResponseEntity.ok(id + " adlı belgenin analiz sonuçları");
    }

}
