server:
  port: 8081

spring:
  application:
    name: reqai-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/reqai_db
    username: reqai_user
    password: reqai_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        enable.idempotence: true
    consumer:
      group-id: reqai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6379}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0  #gelen isteklerin %100 ünü takip et
  otlp:
    tracing:
      endpoint: http://89.168.88.5:4318/v1/traces #temponun otlp http portuna 4318 verileri fırlat

openai:
  api:
    url: https://api.groq.com/openai/v1/chat/completions
    key: ${OPENAI_API_KEY}
    model: llama-3.3-70b-versatile

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN