server:
  port: 8081

spring:
  application:
    name: reqai-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/reqai_db
    username: reqai_user
    password: reqai_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        enable.idempotence: true
    consumer:
      group-id: reqai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}


management:
  endpoints:
    web:
      exposure:
        include: health,info


openai:
  api:
    url: https://api.groq.com/openai/v1/chat/completions
    key: ${OPENAI_API_KEY}
    model: llama-3.3-70b-versatile

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


